# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "npm" # or "maven", "gradle", "pip" etc., depending on the ecosystems used in your project
    directory: "/" # Location of package manifests, e.g., "/" (repository root) or "/path/to/directory"
    schedule:
      interval: "weekly" # Defines how often to check for updates
